### PR TITLE
none recursive trace.toString

### PR DESCRIPTION
**Pull request by hayes**

### CODE REVIEW

**Comment by groundwater** [comment]
cc/ @Raynos

**Comment by groundwater** [comment]
@hayes is `.parent` being set to itself somehow?

**Comment by hayes** [comment]
@groundwater I don't think so, I think this is just for the case where the stacktrace has more than `max callstack size` async components

**Comment by groundwater** [comment]
THAT'S A HUGE TRACE

but lgtm so :shipit:

**Pull request merged**
