### PR TITLE
bump async-listner to 0.4.7

### PR DESCRIPTION
**Pull request by hayes**

### CODE REVIEW

**Comment by groundwater** [comment]
cc @Raynos

**Comment by defunctzombie** [comment]
Only comment I have is the `^` dependency needs to be changed. Please keep dependency style consistent.

**Comment by hayes** [comment]
sorry, fixed the dependency, I have gotten in the habit of just using npm to update my package.json, so I didn't notice.

**Comment by groundwater** [comment]
This will sound pedantic, but can you squash all the commits before merging?

**Pull request merged**
